apiVersion: apps/v1
kind: Deployment
metadata:
  name: Management
  labels:
    app: Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Management
  template:
    metadata:
      labels:
        app: Management
    spec:
      containers:
        - name: Management
          image: username/Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5